### ISSUE TITLE
Change URL references from pdsimg.jpl.nasa.gov to pds-imaging.jpl.nasa.gov

### ISSUE THREAD

**Issue by riverma** [chinapedia/wikipedia.zh-Hant.mediawiki#1]
## Brief Description
The Planetary Data System Imaging Node (PDS-IMG) is deprecating the URL `pdsimg.jpl.nasa.gov`, in place of the more utilized `pds-imaging.jpl.nasa.gov`. References should be updated to ensure links to PDS-IMG continue to work.

## Expected Behavior
- Update all code, README, etc., references of `pdsimg.jpl.nasa.gov` to `pds-imaging.jpl.nasa.gov`

## Current Behavior
- [References](https://github.com/chinapedia/wikipedia.zh.mediawiki/blob/fad73501f8586ea888aa51920caac8bd1257fa06/%E6%96%B9/%E6%96%B9%E5%9D%97%E7%BC%96%E7%A0%81.md) to `pdsimg.jpl.nasa.gov` exist within repository

**Comment by liruqi** [comment]
Please change it on wikipedia.org first.
